package util;

public enum Routes {
    ATTENDANCE,CATEGORY,CREATE_NEW_ACCOUNT,CUSTOMER,GMDASHBOARD,EMPLOYER,FOGOT_MY_PASSWORD,ITEM,GMLOGIN,ORDER_DETAIL,ORDER,ORDER_PAYMEMT,SALARY,SUPPLIER,SUPPLIER_ORDER,CASHIER_LOGIN,CASHIER_DASHBOARD,STOCK_MANAGER_DASHBOARD,STOCK_MANAGER_LOGIN,MAIN_LOGIN
}
